#!/bin/bash


function _help(){
    echo "
    Argumentos posicionais.
        dir   Diretório alvo da auditoria de mudanças.
    

    Argumentos opcionais.
        --help  Imprime essa mensagem de ajuda.
    "
}

function _file_exists_(){
    _path=$1

    if  [ -e $_path ]; then
        echo "File $_path: Ok"
    else
        echo "token file - date" > $_path
        echo "Created file $_path"
    fi
}

function _check_removeds_(){
    _ad_file=$1
    _list=$2

    x=$( cut $_ad_file -d' ' -f2 )
    _files=$( cut $x -d; -f1 )

    while read _file;do
        _exist=$( echo $_list | grep $_file)

        if [ ! $_exist ];then
            sed -i "/$_files/d" $_ad_file
            echo "REMOVED $_file"
        fi
    done < $_files

}

function _report_(){
    _file=$1
    _data=$2

    _file_exists_ $_file
    echo $_data >> $_file
}

function main(){
    _dir=$1
    _ad_file="$_dir/auditoria.csv"
    _rp_file="$_dir/relatório.csv"
    _date=$( date +"%F %R" )
    _list=$(ls -la $_dir)

    _file_exists_ $_ad_file

    while read _line; do
        _content=$( cat $_ad_file | grep $_line )

        if [ ! $_content ];then
            _data="$( md5sum "$_dir/$_line") - $_date"
            echo $_data >> $_ad_file
            _report_ $_rp_file $_data
            echo "ADD $_line"
        else
            _tmp1="audtkn.tmp"
            _tmp2="fltkn.tmp"
            _data=$( echo $_line | md5sum )
            
            echo $( cut $_content -d\- -f1 ) > $_tmp1
            echo $_data > $_tmp2

            if [[ "$( md5sum $_tmp1 )" != "$( md5sum $_tmp2 )" ]];then
                _new_content="$_data - $date"
                sed -i "s/$_content/$$_new_content/g" "$_dir/$_line"
                _report_ $_rp_file $_new_content
                echo "CHANGED $_line"
            fi
        fi
    done < $_list

    _check_removeds_ $_audit_file $_list

}

if [ ! $1 -o $1 == "--help" ]; then
    _help
else
    main $1
fi
