#!/bin/bash


function _help(){
    echo "
    Argumentos posicionais.
        dir   Diretório alvo da auditoria de mudanças.
    

    Argumentos opcionais.
        --help  Imprime essa mensagem de ajuda.
    "
}

function __file_exists__(){
    _path=$1

    if  [ -e $_path ]; then
        echo "File $_path: Ok"
    else
        echo "Created file $_path"
    fi
}

function __check_removeds__(){
    _ad_file=$1
    _list=$2
    _files=$( cut $_ad_file -d\- -f2 )

    for _file in $( echo $_files | cut -d' ' -f2);do
        _exist=$( echo $_list | grep $_file)

        if [ $_exist ];then
            sed -i "/$_files/d" $_ad_file
            echo "REMOVED $_file"
        fi
    done

}

function __report__(){
    _report_path=$1
    _data=$2

    echo $_data >> $_report_path
}

function __first_audit__(){
    _path=$1
    _ad_file=$2
    _rp_file=$3
    _files=$4

    for _file in $_files;do
        _hash=$( md5sum "$_path/$_file")
        echo $_hash >> $_ad_file
        echo "ADD $_hash"
        __report__ $_rp_file "$_hash - $( date +"%F %R" )"
    done
}

function __add__(){
    _ad_file=$1
    _list=$2
    _path=$3
    _rp_file=$4

    for _file in $_list;do
        _exist=$( cat $_ad_file | grep $_file )

        if [ ! "$_exist" ];then
            _hash=$( md5sum "$_path/$_file" )
            echo $_hash >> $_ad_file
            echo "ADD $_path/$_file"
            __report__ $_rp_file $( echo "$_hash - $( date +"%F %R" )")
        fi
    done
}

function main(){
    _dir="$1"
    _ad_file="$_dir/auditoria.txt"
    _rp_file="$_dir/relatório.txt"
    _list=$(ls $_dir)
    __file_exists__ $_ad_file
    __file_exists__ $_report_path
    _checked_sum=$( md5sum -c $_ad_file )

    if [ ! "$_checked_sum" ];then
        __first_audit__ $_dir $_ad_file $_rp_file "$_list"
    else
        _status=$(echo $_checked_sum | cut -d' ' -f2)

        if [ ! "$_status" == "SUCESSO" ] && [ ! "$_status" == "SUCCESS" ];then
            _file=$( echo $_checked_sum | cut -d: -f1 )
            _old_hash=$( cat $_ad_file | grep $_file )
            sed -i "/$_old_hash/d" $_ad_file
            echo $_hash >> $_ad_file
            echo "UPDATE $_file"
            __report__ $_rp_file $( echo "$_hash - $( date +"%F %R" )")
        fi

        __add__ $_ad_file "$_list" $_dir $_rp_file
        __check_removeds__ $_ad_file "$_list"

    fi
}

if [ ! $1 -o $1 == "--help" ]; then
    _help
else
    main $1
fi
